#!/bin/bash 
# Hacked together by Mike Harris
# Vast majority of script stolen from sslthing.sh by blh@blh.se
#
openssl=/usr/bin/openssl
###### END OF CONFIGURATION #####
# Print Usage Info
if  [ ! $1 ]; then
  echo "Syntax: $0 HOST:SSLPORT [-v]"
  exit 1
fi
# Fix path to OpenSSL
if  [ ! -e $openssl ]; then
  echo "Please correct path to OpenSSL $0"
  exit 2
fi
## Create temp file to do some actions in
SSLCHECKTMP=$(mktemp /tmp/sslcheck.XXXXXXXXXXXX) || { echo "Failed to create temp file"; exit 1; }
##
## Make a request
echo "GET / HTTP/1.1" > $SSLCHECKTMP
#
## Request available ciphers from openssl and test them
for ssl in -ssl2 -ssl3 -tls1
#for ssl in -ssl3 -tls1 -tls1_1 -tls1_2 
do
  echo "Testing `echo $ssl | cut -c2- | tr "a-z" "A-Z"`..."
  $openssl ciphers $ssl -v | while read line
  do
    cipher=`echo $line | awk '{print $1}'`
    bits=`echo $line | awk '{print $5}' | cut -f2 -d\( | cut -f1 -d\)`
    if [ $2 ]; then
      echo -n "$cipher - $bits bits..."
    fi

    if ($openssl s_client $ssl -cipher $cipher -connect $1 < $SSLCHECKTMP 2>&1 | egrep ^New | egrep -v NONE  > /dev/null); then
      if [ $2 ]; then
        echo "OK"
      else
        echo "$cipher - $bits bits"
      fi
    else
      if [ $2 ]; then
        echo "Failed"
      fi
    fi
  done | grep -v error
done

## Remove temporary file
rm -f $SSLCHECKTMP
exit 0

